name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build Skyflow iOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build
        run: |
          xcodebuild clean build \
            -project Skyflow/Skyflow.xcodeproj \
            -scheme Skyflow \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO